services:
  node:
    image: ethereum/client-go:v1.13.5
    ports:
      - "${NODE_PORT}:8545"
    command: [ "--miner.gaslimit", "12000000", "--http", "--http.api", "personal,eth,net,web3,debug", "--http.vhosts", "*,localhost,host.docker.internal", "--http.addr", "0.0.0.0", "--allow-insecure-unlock", "--rpc.allow-unprotected-txs", "--dev", "--verbosity", "2", "--nodiscover", "--maxpeers", "0", "--mine", "--networkid", "1337" ]

  bundler:
    build:
      context: .
      dockerfile: Dockerfile.bundler
    ports:
      - "${BUNDLER_PORT}:${BUNDLER_PORT}"
    command: [ "yarn", "run", "bundler", "--network", "http://node:${NODE_PORT}" ]
    depends_on:
      - node
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${BUNDLER_PORT}/" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  scanner:
    image: otterscan/otterscan:latest
    ports:
      - "${SCANNER_PORT}:80"
